### ISSUE TITLE
npm run dev failed : 'ELECTRON_ENABLE_LOGGING' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by nasirdavinci** [jooy2/vutron#137]
**Describe the bug**
I have installed the pachage through the "NPM INIT VUTRON" it completed succesfully  but throwing the error  'ELECTRON_ENABLE_LOGGING' is not recognized as an internal or external command

CMD
----------------------
\web\lab\vutron>npm run dev

> vutron@1.0.0 dev
> ELECTRON_ENABLE_LOGGING=true vite

'ELECTRON_ENABLE_LOGGING' is not recognized as an internal or external command,
operable program or batch file.
-------------------------

**Device information (please complete the following information):**
 - OS Name: WINDOWS 11
 - npm version:  9.6.7

**Comment by nasirdavinci** [comment]
As i guessed i needed to remove
ELECTRON_ENABLE_LOGGING=true 

from package.json > scripts > dev

and it fixed the issue but is there any good solution  ?

**Comment by jooy2** [comment]
Hello, thank you for using the `vutron` template.

The problem was caused by not being able to set the environment variables smoothly in the Windows environment - this is my mistake!

I've fixed it, and if you reinstall the package with `npm i` from your master code (after `git pull`) and try again, it should work.

If you have any questions in the future, feel free to open an issue. If you found the project helpful, please leave a star to `vutron` repository.

Thanks.
