### ISSUE TITLE
npm init vutron tip error

### ISSUE THREAD

**Issue by NJHSFNAK** [jooy2/vutron#191]
**Describe the bug**
After executing the npm init vutron command, the console prompts the error。
<img width="570" alt="image" src="https://github.com/jooy2/vutron/assets/38530519/77fea950-29e0-425e-92e7-fa76a84572c8">

Node Version: 18.14.1
Npm Version: 9.8.1

**Device information (please complete the following information):**
 - OS Name:  macOS
 - OS Version: 13.6.7

**Comment by jooy2** [comment]
Hello! Thank you for using vutron.

This doesn't seem to be an issue with the vutron package, as the problem is not generally reproducible.
It is probably a temporary error in the npm network, or a problem with your system network settings.

If your npm proxy settings are incorrect, you can reset them with the following command:

```shell
$ npm config get proxy
$ npm config rm proxy
$ npm config rm https-proxy
```

Could you please check if the problem persists after running the `npm init vutron` command again?

Regards,

**Comment by NJHSFNAK** [comment]
thanks
