### ISSUE TITLE
Embed the web server into the main process

### ISSUE THREAD

**Issue by vk22** [jooy2/vutron#194]
I don't know if this is correct, but I need to embed the web server into the main process. Web server on express, with routers, controllers, etc. 
It's a separate folder in root with all the files inside. 
I do require in the src/main/index.ts 
`require(‘../../server/index’)`
and in dev mode everything works fine. 
But when i do build it doesn't work. 
Can you tell me how to fix it?
Thanks in advance!

**Comment by jooy2** [comment]
Hello, thank you for using the vutron template.

Your description does not provide enough information for us to identify the issue.
Please leave a detailed error message or code about the issue, what is happening and how to reproduce it.

Vutron is ESM oriented, please use import instead of require.

Currently, the paths that the `vite.config.mts` file references when building are `preload`, `main`, and `renderer` in the `src` path. If you want to include other directories in the build path, you may need to consult the `vite.config.mts` file to map those paths.

**Comment by vk22** [comment]
Hi! Thank you for you answer and thank your for Vutron!
I have already solved my question.
All the best!

**Comment by jooy2** [comment]
Hello. Thank you for letting me know the status. If you have any other questions, please feel free to open an issue!
