### ISSUE TITLE
Excuse me, can this project be applied in production environment?

### ISSUE THREAD

**Issue by 593496637** [jooy2/vutron#6]

**Comment by jooy2** [comment]
While creating the Vutron project, the production build was also tested. Build results in production environment according to actual requirements may vary, so you should try packaging through the build command.

If you're talking about licenses, this open source is under the MIT license. It can also be used in commercial projects as long as it is properly specified under the [MIT license](https://github.com/jooy2/vutron/blob/master/LICENSE).

If the issue is not described here, please update a detailed description.
