### ISSUE TITLE
Run dev

### ISSUE THREAD

**Issue by neuralsys** [jooy2/vutron#7]
Hi,
i have problem with npm run dev.

After npm install i try to run npm run dev and Im getting this

vite v3.2.3 building for development...

watching for file changes...

build started...
transforming (1) src/main/index.tsdist/preload/index.js   0.07 KiB / gzip: 0.08 KiB
built in 97ms.
transforming (5) node_modules/@electron/remote/dist/src/main/objects-registry.jsError launching app
Unable to find Electron app at /home/ibakran/Downloads/vutron-master

Cannot find module '/home/ibakran/Downloads/vutron-master/dist/main/index.js'. Please verify that the package.json has a valid "main" entry
✓ 24 modules transformed.

Thanks

**Comment by jooy2** [comment]
Hello. Thank you for using Vutron Template.

This problem seems to be caused by the Electron app not finding the entry file.

```shell
Unable to find Electron app at /home/ibakran/Downloads/vutron-master
```

Can you confirm that the `dist` directory and `dist/main/index.js` file are built correctly when running `npm run dev`?

If the problem persists, can you reply with more additional details?
Example: Using OS and NodeJS version you tried, or if there is a modified file, etc.

Thanks.
